### ISSUE TITLE
Plugin breaks documentation popups

### ISSUE THREAD

**Issue by innervation** [42Crunch/intellij-openapi-editor#1]
When using version 1.3, the tooltips in IntelliJ IDEA Ultimate 2020.2 go from this:

![image](https://user-images.githubusercontent.com/1087130/100098901-abc22c00-2e2c-11eb-9f0d-326afda9702b.png)

to this:

![image](https://user-images.githubusercontent.com/1087130/100099042-de6c2480-2e2c-11eb-87fb-df3d32a3a858.png)

The blue boxes cover other fields such as `see also` and `api notes`.

IntelliJ version info:

IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Non-Bundled Plugins: GLSL, PlantUML integration, YAML/Ansible support, com.crunch42.openapi, com.github.gilday.darkmode, com.github.leomillon.uuidgenerator, Lombook Plugin, com.dubreuia, com.jetbrains.php.framework, com.intellij.plugins.watcher, com.kondratevpavel.plugins.goland.gomethodgenerator, ideanginx9, io.protostuff.protostuff-jetbrains-plugin, main.kotlin.com.jimschubert.intellij.swaggercodegen, org.jetbrains.plugins.go-template, name.kropp.intellij.makefile, org.zalando.intellij.swagger, org.sylfra.idea.plugins.linessorter, org.toml.lang, Karma, org.jetbrains.plugins.vue, com.intellij.plugins.html.instantEditing, Pythonid, org.jetbrains.plugins.go, com.ypwang.plugin.go-linter, net.ashald.envfile

**Comment by ak1394** [comment]
This issue should be resolved in the recent versions of the plugin.
