### ISSUE TITLE
Does not support `{}` in filenames (redocly style)

### ISSUE THREAD

**Issue by nesl247** [42Crunch/intellij-openapi-editor#13]
We're using the redocly style of naming files and getting a bunch of `Failed to parse $ref: Illegal character in path at index 12: paths/files@{id}.yaml` due to the `{}` in the filename.

https://redoc.ly/docs/resources/multi-file-definitions/

**Comment by ak1394** [comment]
We use java.net.URI internally for processing multi-file OpenAPI files, and it does not accept unencoded curly braces as a part of URI. You can try encoding { and } to %7B and %7D.
