### ISSUE TITLE
External references are not properly resolved using relative location

### ISSUE THREAD

**Issue by anikitin** [42Crunch/intellij-openapi-editor#15]
When I use $ref to refer a schema from external file (using relative path) the plugin incorrectly tries to locate this file relatively to "temp" directory, not the directory of main spec file. The expected behavior is described here: [https://swagger.io/docs/specification/using-ref/](https://swagger.io/docs/specification/using-ref/):

> Remote Reference – $ref: 'document.json' Uses the whole document located on the same server and in the same location.
> - The element of the document located in the same folder – $ref: 'document.json#/myElement'
> - The element of the document located in the parent folder – $ref: '../document.json#/myElement'
> - The element of the document located in another folder – $ref: '../another-folder/document.json#/myElement'

See attached file with an example. Plugin displays the error: 
**ENOENT: no such file or directory, open 'c:\Users\....\AppData\Local\Temp\included-openapi.yml'**

Same file is successfully processed with VS Code, Swagger Editor, etc.

[ref-issue.zip](https://github.com/42Crunch/intellij-openapi-editor/files/8347592/ref-issue.zip)

**Comment by vfateev** [comment]
It will work correctly only if the folder or files are located inside an IDEA project.

**Comment by anikitin** [comment]
Oh, it seems that this issue is not about this plugin, but another (Spectral) one. Sorry for confusion, I will close this one.
I submitted the issue in that project: https://github.com/SchwarzIT/spectral-intellij-plugin/issues/11
