### ISSUE TITLE
Unable to display preview window, seems stuck with Internet Explorer

### ISSUE THREAD

**Issue by paul-avisseau** [42Crunch/intellij-openapi-editor#18]
Hi,

I'm unable to view the preview window on the right side, it is always blank. When right-clicking on it, the dropdown menu looks like Internet Explorer. And IE was the original system browser on my laptop, even though I changed it for Chrome a long time ago. Tried to change the default preview browser to Chrome in Settings > Tools > Web Browsers and Preview, but with no effect. I'm using IntelliJ IDEA Ultimate 2022.1. Does the preview window always use the default system browser?

![image](https://user-images.githubusercontent.com/40549270/163055990-3c6458aa-40d3-4371-b4cf-af636e7f06f9.png)

**Comment by ak1394** [comment]
Thanks for opening an issue. Could you confirm the plugin version? How do you invoke a preview? By the looks of it, it might be a different plugin opening Internet Explorer window, not the 42Crunch
OpenAPI ​(Swagger)​ Editor.

**Comment by Rossojo** [comment]
For the people that are, like me, brought here by google. This is a bug in the bundled openapi plugin of IntelliJ. Details can be found in the IntelliJ bug tracker: https://youtrack.jetbrains.com/issue/IDEA-291069/Swagger-UI:-Preview-only-shows-a-blank-page

**Comment by Rest11** [comment]
Many thank you, @Rossojo 
On Mac it works
but the path was for my IDE `~Library/Caches/JetBrains/WebStorm2022.1`

```
Workaround:

In the 2022.1.1:
Removing the below folder and restart the IDE:

Windows: C:\Users<user_name>\AppData\Local\JetBrains\IntelliJIdea2022.1\openapi\
Linux: ~/.cache/JetBrains/IntelliJIdea2022.1/openapi/
MacOS: ~/Library/Caches/JetBrains/IntelliJIdea2022.1/openapi/
```
