### ISSUE TITLE
Curly braces in the $ref are failing validation

### ISSUE THREAD

**Issue by JakubKahovec** [42Crunch/intellij-openapi-editor#21]
When referencing a path which contains curly braces

`$ref: '#/paths/~1blogs~1{blog_id}~1new~0posts`

 there is a validation issue complaining about invalid characters.

**Comment by ak1394** [comment]
You should URL encode curly braces {} as %7B %7D you can get a bit more background info here https://stackoverflow.com/questions/23064605/when-if-ever-should-characters-like-and-curly-braces-be-percent-encoded

Implementation-wise, we parse $ref's with java URI which fails on unencoded {} in URIs.

**Comment by JakubKahovec** [comment]
I see, it works with the encoded chars. 
Thank you
