### ISSUE TITLE
CORS error when executing a POST request

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [42Crunch/intellij-openapi-editor#23]
I generated the swagger html page using the plugin, it creates and serves it correctly (swaggerui.html), but when I try to execute an example request, it fails with CORS error:
```
blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by ak1394** [comment]
Hi @WhyINeedToFillUsername ! The Swagger UI preview runs in the browser and therefore must abide by CORS rules. So most likely, your server does not reply with proper CORS headers and therefore Swagger UI can't access the server response.

**Comment by WhyINeedToFillUsername** [comment]
Hi, thank you for the reply. I will take a look at if we allow localhost or what CORS headers we send here.
