### ISSUE TITLE
Preview button disables when there are validation errors in the document, but no errors are highlighted in source

### ISSUE THREAD

**Issue by alexpyattaev** [42Crunch/intellij-openapi-editor#32]
Whenever one adds some error into the document, it is occasionally possible to have a document which has
no highlighted errors, but preview button is grayed out. In this case, one is forced to use external validator to fix the syntax errors first, and only then the preview works.

**Comment by vfateev** [comment]
Could you share an example of the file with an error not highlighted by the IDE?
In general we rely on the IDE to validate and highlight json and yaml files. We also have a simple tooltip in the OpenAPI tree if content parsing failed, it may help to understand the reason.
![image](https://user-images.githubusercontent.com/16338532/223052887-ab327548-0efb-41ca-98a1-9853dcfb8fd6.png)

**Comment by alexpyattaev** [comment]
It seems I am unable to replicate the issue on any of the documents, including the ones where it happened consistently. Whatever the problem was, it went away when I started trying to reproduce it (as it always goes with bugs). If I manage to reproduce reliably, I'll let you know. Sorry!
