### ISSUE TITLE
点击运行后直接报错，目前不知道什么原因

### ISSUE THREAD

**Issue by 1484117468** [42Crunch/intellij-openapi-editor#42]
![image](https://github.com/42Crunch/intellij-openapi-editor/assets/52945808/c34a3af1-4d44-426d-abca-af697594c9df)

**Comment by 1484117468** [comment]
在goland2023.3 openapi 版本1.72

**Comment by ak1394** [comment]
看起来错误来自不同的扩展，而不是 OpenAPI (Swagger) Editor
