### ISSUE TITLE
Rider - cant run preview, this file is not part of the project

### ISSUE THREAD

**Issue by kkd83** [42Crunch/intellij-openapi-editor#7]
JetBrains Rider 2021.1.2

![image](https://user-images.githubusercontent.com/76164686/118671346-4b1a1780-b7ef-11eb-9773-e018f113b773.png)

Neither preview or security audit runs as the file is not part of the project - it cant really be part of a project in rider (c#). Any ideas on how to get around this or a fix?

**Comment by ak1394** [comment]
Hi @kkd83 ! Being a part of a project means it should reside in the same folder with the rest of your files, so if you open project with "File -> Open" and choose a folder, OpenAPI files should be in that folder.

It doesn't mean OAS file should be a part of your C# project.

**Comment by kkd83** [comment]
I have as a directory structure; would you expect it to be at the solution level?
/ 
....mysolution.sln
..../src
........... directories and proj files
..../docs
......../external-api
............/external-api.yaml                     <--- my api docs yaml file to edit and preview

**Comment by ak1394** [comment]
No, that actually looks good to me, as long as you do File -> Open on your root directory folder, and then open your "external-api.yaml". Can you confirm that you do that?

The scenario we don't support, for example is when you have an open project located at "C:\foo" and then you do File -> Open and open addition file from "C:\bar\openapi.yaml" and try to preview this.

**Comment by kkd83** [comment]
Can confirm that if I open using select folder in the base (which contains the sln and docs) then the plug in still complains about not being part of the project. I dont know if this is a rider vs intellij issue?

**Comment by kkd83** [comment]
Ah ha - fixed it, had to right click on the solution and "Add existing folder". thanks @ak1394

**Comment by ak1394** [comment]
Thanks for the info @kkd83 !
