### ISSUE TITLE
Problems view shows "Schema validation: Missing required property '$ref'" instead of correct error message

### ISSUE THREAD

**Issue by strmenskym** [42Crunch/intellij-openapi-editor#9]
Hi, 

I'm facing problem that openapi-editor shows incorrect error message instead of correct one.
Step to reproduce:
1. take valid yaml file
2. change e.g. "type" to non existing "long". 
3. problems view shows error: "Schema validation: Missing required property '$ref'" on that line number.

You can see it on attached screenshot.
Version of openapi editor 1.18
Version of InteliJ 2021.1.3 (Community edition)
![screenshot-20210716-132936](https://user-images.githubusercontent.com/6916688/125942276-8ea0e420-9b2f-4cf3-8d2d-00fa8424beac.png)

**Comment by ak1394** [comment]
Hi @strmenskym ! Thanks for reporting the issue. Unfortunately this is the limitation of IntelliJ which implements the schema validation (our plugin simply supplies OpenAPI schema for IntelliJ to use).

Alternatively, you can invoke our "Security Audit" which implements better schema checking, and in this case will return following error message:

    The value 'long' of the property 'type' is not in the enum 'string, number, integer, boolean, array, object' 
    that the OpenAPI Specification allows for this property

**Comment by strmenskym** [comment]
Hi @ak1394,

Thank you for your prompt answer. 
Ok, I understand that I need to use another tool for validating my specs. 
But it is strange that schema validation returns non-existing problem. But it might be a problem of somebody else.

Thank you for help.

**Comment by ak1394** [comment]
You're welcome! And the message is not _that_ wrong, in the schema there you either need to have a valid schema object (with valid type, etc) or valid reference (that's where $ref comes to play). Apparently IntelliJ decides if that's not a valid schema, then maybe it should be a reference...
